# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["contracts/*"]

#[profile.release.package.cw20-base-dogether]
#codegen-units = 1
#incremental = false

#[profile.release.package.dogether]
#codegen-units = 1
#incremental = false

#[profile.release.package.loterra-staking-contract]
#codegen-units = 1
#incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false